stages:
  - build

build_image:
  stage: build
  image: docker:24.0.5 # משתמש ב-Docker כדי לבנות Docker
  services:
    - docker:24.0.5-dind # Docker-in-Docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest